### ISSUE TITLE
iPhone app no longer working -critical issue

### ISSUE THREAD

**Issue by attraides** [bada-studio/knights_support#23]
iPhone app verification no longer works it seems.

See telegram for number of people effected. Just started in the last 10 hrs or so ie overnight for me in New zealand

**Comment by attraides** [comment]
App can no longer be verified

**Comment by Rishi556** [comment]
Why isn't it in the app store?

**Comment by mj-raindays** [comment]
It was fixed.

@Rishi556 
That's because 'Apple' does not allow crypto games.
