### ISSUE TITLE
전투 중 아이템 변경 시 문제 발생

### ISSUE THREAD

**Issue by declear** [bada-studio/knights_support#3]
1. 3명 중 2명이 죽고 한명이 거의 빈사 직전 아이템을 해제
2. 전멸 상태로 화면 전환됨
3. 아이템 다시 장착 시 죽었던(?) 케릭터가 부활하여 다시 전투 시작!!

**Comment by mj-raindays** [comment]
이 이슈는 일종의 한계입니다 ㅠㅠ
체인내에서 실시간으로 처리하면 CPU를 감당할 수 없기 때문에, 
현재 차고 있는 장비를 기준으로, 지난 부활부터 현재까지의 스탯을 계산하기 때문에 발생합니다.
반대로 벗어버린 장비들의 스탯은 적용이 안됩니다.
