### ISSUE TITLE
추천인 보상에서 추천인 계정 이름을 넣을 수가 없습니다

### ISSUE THREAD

**Issue by nc0619** [bada-studio/knights_support#6]
![b1](https://user-images.githubusercontent.com/41664200/45259182-408afd00-b37b-11e8-84c2-90bb4328b2eb.png)

추천인 계정 이름 넣는곳이 활성화가 안되어서 계정 이름을 넣을 수가 없습니다
왜 안되는지요?

**Comment by mj-raindays** [comment]
해상도가 낮은 pc에서 커서가 잘 안보이는 이슈가 있습니다. ㅠ 
커서 두께를 바꿔둘께요.
그냥 키보드를 치시면 입력될꺼에요
