### ISSUE TITLE
내 아이템 오른쪽 위에 나타나는 노란 표시는 뭔가요?

### ISSUE THREAD

**Issue by nc0619** [bada-studio/knights_support#7]
![b2](https://user-images.githubusercontent.com/41664200/45259222-6bc21c00-b37c-11e8-9359-fa46a24d5f9d.png)

이 표시가 자꾸 눈에 거슬리는데 어떻게 하면 없어지나요?

**Comment by mj-raindays** [comment]
착용 가능한 다른 옵션이 있다는 의미입니다. 
옵션에서 저 표시를 끄고 킬수 있게 있도록 해볼께요~

**Comment by mj-raindays** [comment]
설정에 반영되었습니다~
